name: Build and push Docker image to GHCR

permissions:
  packages: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "."
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build Docker Image"
        run: docker build . --tag ghcr.io/tlaanemaa/${{ github.event.repository.name }}:latest

      - name: "Push Docker Image"
        run: docker push ghcr.io/tlaanemaa/${{ github.event.repository.name }}:latest